Ljms\CoreBundle\Entity\Profile:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields: email
           message: This email is already used.
    group_sequence:
        - Profile
        - Add
    properties:
        first_name:
                  - NotBlank:
                      message: Field First Name is required.
                  - Length:
                      min: 2
                      max: 100
        last_name:
                  - NotBlank:
                      message: Field Last Name is required.
                  - Length:
                      min: 2
                      max: 100
        email:
                  - NotBlank:
                      message: Field Email is required.
                  - Length:
                      max: 100
        password:
                  - NotBlank:
                      groups: [Add]
                      message: Field Password is required.
                  - Length:
                      min: 5
                      max: 30
        home_phone:
                  - NotBlank:
                      message: Field Home Phone is required.
                  - Length:
                      max: 15
        cell_phone:
                  - Length:
                      max: 15
        alt_phone:
                  - Length:
                      max: 15
Ljms\CoreBundle\Entity\Address:
    properties:
        address:
                  - NotBlank:
                      message: Field Address is required.
                  - Length:
                      max: 100
        state:
                  - NotBlank:
                      message: Field State is required.
        city:
                  - NotBlank:
                      message: Field City is required.
                  - Length:
                      max: 100
        zip:
                  - NotBlank:
                      message: Field Zip is required.
                  - Length:
                      max: 15
Ljms\CoreBundle\Entity\AltContact:
    properties:
        altFirstName:
                  - Length:
                      max: 100
        altLastName:
                  - Length:
                      max: 100
        altEmail:
                  - Length:
                      max: 100
        altPhone:
                  - Length:
                      max: 15
Ljms\CoreBundle\Entity\Player:
    group_sequence:
            - Player
    properties:
        first_name:
                  - NotBlank:
                      message: Field First Name is required.
                  - Length:
                      min: 2
                      max: 100
        last_name:
                  - NotBlank:
                      message: Field Last Name is required.
                  - Length:
                      min: 2
                      max: 100
        birth_date:
                  - Date: ~
        note:
                  - Length:
                      max: 500
Ljms\CoreBundle\Entity\PlayerRegistration:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields: jersey_number
               message: This Number is already used.
    properties:
        jersey_name:
                  - NotBlank:
                      message: Field Jersey Name is required.
                  - Length:
                      min: 2
                      max: 100
        jersey_number:
                  - NotBlank:
                      message: Field Jersey Number is required.
                  - Length:
                      min: 1
                      max: 3
        shirt_type:
                  - NotBlank:
                      message: Field Shirt Type is required.
        short_type:
                  - NotBlank:
                      message: Field Short Type is required.
        shirt_size:
                  - NotBlank:
                      message: Field Shirt Size is required.
        short_size:
                  - NotBlank:
                      message: Field Short Size is required.
Ljms\CoreBundle\Entity\Division:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields: name
               message: This Division name is already used.
    properties:
        is_active:
                  - NotBlank:
                      message: Field Is active is required.
        name:
                  - NotBlank:
                      message: Field Division Name is required.
                  - Length:
                      max: 100
        min_age:
                  - NotBlank:
                      message: Field Min age is required.
        max_age:
                  - NotBlank:
                      message: Field Max age is required.
        description:
                  - Length:
                      max: 500
        rules:
                  - Length:
                      max: 500
        file:
                  - Image:
                      maxWidth: 640
                      maxHeight: 480
                  - File:
                      maxSize: 5M
Ljms\CoreBundle\Entity\Team:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields: name
               message: This Team name is already used.
    properties:
        is_active:
                  - NotBlank:
                      message: Field Is active is required.
        name:
                  - NotBlank:
                      message: Field Team Name is required.
                  - Length:
                      max: 100
        division:
                  - NotBlank:
                      message: Field Division is required.
        traveling:
                  - NotBlank:
                      message: Field is Visitor is required.
Ljms\CoreBundle\Entity\Schedule:
    properties:
        date:
                  - Date: ~
        home_team:
                  - NotBlank:
                      message: Field Home Team is required.
        visiting_team:
                  - NotBlank:
                      message: Field Visiting Team is required.
        location:
                  - NotBlank:
                      message: Field Location is required.
        home_team_score:
                  - Length:
                      max: 3
        visiting_team_score:
                  - Length:
                      max: 3
Ljms\CoreBundle\Entity\Location:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields: name
               message: This Location name is already used.
    properties:
        name:
                  - NotBlank:
                      message: Field Name is required.
                  - Length:
                      max: 100
        city:
                  - Length:
                      max: 100
        address:
                   - Length:
                      max: 100
        state:
                  - NotBlank:
                      message: Field State is required.
        zip:
                  - Length:
                      max: 15
        phone:
                  - Length:
                      max: 15
        is_active:
                  - NotBlank:
                      message: Field Is active is required.
        site_url:
                  - Length:
                      max: 100
