security:
    role_hierarchy:
        ROLE_ADMIN:   [ROLE_DIRECTOR, ROLE_COACH, ROLE_MANAGER, ROLE_GUARDIAN]
    encoders:
        Ljms\CoreBundle\Entity\Profile:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    providers:
          main:
              entity: { class: LjmsCoreBundle:Profile, property: email }
    firewalls:
            secured_area:
                pattern:    ^/
                anonymous: ~
                form_login: 
                    login_path: /admin
                    check_path: /login_check
                logout:
                    path:   /logout
                    target: /home
    access_control:
        - { path: ^/admin/users , roles: ROLE_ADMIN }
        - { path: ^/admin/guardian/add , roles: ROLE_ADMIN }
        - { path: ^/admin/division/add , roles: ROLE_ADMIN }
        - { path: ^/admin/guardian , roles: ROLE_GUARDIAN}
        - { path: ^/admin/players , roles: [ROLE_GUARDIAN, ROLE_COACH]}
        - { path: ^/admin/division , roles: ROLE_DIRECTOR}
        - { path: ^/admin/teams/assign , roles: ROLE_COACH }
        - { path: ^/admin/teams/edit , roles: ROLE_DIRECTOR }
        - { path: ^/admin/teams/add , roles: ROLE_DIRECTOR }
        - { path: ^/admin/teams , roles: [ROLE_DIRECTOR, ROLE_COACH, ROLE_MANAGER]}
        - { path: ^/admin/schedule/add , roles: ROLE_MANAGER }
        - { path: ^/admin/schedule/edit , roles: ROLE_MANAGER }
        - { path: ^/admin/schedule/result , roles: ROLE_MANAGER }
        - { path: ^/admin/schedule , roles: [ROLE_COACH, ROLE_MANAGER] }
        - { path: ^/admin/location , roles: ROLE_MANAGER }





