home_index:
    pattern:  /home
    defaults: { _controller: LjmsHomeBundle:Home:index }
about_index:
    pattern:  /about
    defaults: { _controller: LjmsHomeBundle:About:index }
sponsors_index:
    pattern:  /sponsors
    defaults: { _controller: LjmsHomeBundle:Sponsors:index }

schedule_get:
    pattern:  /home/get
    defaults: { _controller: LjmsHomeBundle:Home:get }